import { ONG, Project, GovernanceRequirement } from './types';

export const INITIAL_GOVERNANCE_REQUIREMENTS: GovernanceRequirement[] = [
  // BRONZE LEVEL (Básico)
  {
    id: 'req_b1',
    title: 'Estatuto Social Atualizado e Registrado em Cartório',
    description: 'Estatuto adequado à legislação vigente (Código Civil / MROSC Lei 13.019/14) com finalidade pública bem definida.',
    level: 'Bronze',
    category: 'Jurídico & Estatutário',
    requiredForLegalCompliance: true,
    checked: true,
  },
  {
    id: 'req_b2',
    title: 'CNPJ Ativo na Receita Federal há pelo menos 1 ano',
    description: 'Comprovante de Inscrição e de Situação Cadastral Ativa e sem pendências cadastrais graves.',
    level: 'Bronze',
    category: 'Jurídico & Estatutário',
    requiredForLegalCompliance: true,
    checked: true,
  },
  {
    id: 'req_b3',
    title: 'Ata de Eleição da Diretoria Vigente',
    description: 'Ata registrada com mandato dos dirigentes dentro do prazo de validade.',
    level: 'Bronze',
    category: 'Jurídico & Estatutário',
    requiredForLegalCompliance: true,
    checked: true,
  },
  {
    id: 'req_b4',
    title: 'Certidão Negativa de Débitos (CND) Federal e FGTS',
    description: 'Certidões que comprovam regularidade fiscal com a União e obrigações trabalhistas/previdenciárias.',
    level: 'Bronze',
    category: 'Financeiro & Contábil',
    requiredForLegalCompliance: true,
    checked: true,
  },
  {
    id: 'req_b5',
    title: 'Conta Bancária de Uso Exclusivo da Organização',
    description: 'Conta pessoa jurídica para movimentação dos recursos e repasses de convênios.',
    level: 'Bronze',
    category: 'Financeiro & Contábil',
    requiredForLegalCompliance: true,
    checked: true,
  },

  // PRATA LEVEL (Intermediário)
  {
    id: 'req_p1',
    title: 'Balanço Patrimonial e DRE Assinados por Contador',
    description: 'Demonstrações contábeis do último exercício fiscal em conformidade com as ITG 2002 (R1).',
    level: 'Prata',
    category: 'Financeiro & Contábil',
    requiredForLegalCompliance: true,
    checked: true,
  },
  {
    id: 'req_p2',
    title: 'Portal de Transparência ou Prestação de Contas Pública',
    description: 'Divulgação online de receitas, despesas, parecer contábil e projetos executados.',
    level: 'Prata',
    category: 'Transparência & Gestão',
    requiredForLegalCompliance: false,
    checked: false,
  },
  {
    id: 'req_p3',
    title: 'Regimento Interno e Manual de Compras/Contratações',
    description: 'Normas claras de seleção de fornecedores, cotação de preços e reembolso de despesas.',
    level: 'Prata',
    category: 'Transparência & Gestão',
    requiredForLegalCompliance: false,
    checked: true,
  },
  {
    id: 'req_p4',
    title: 'Inscrição no Conselho Municipal da Criança/Idoso ou Assistência Social',
    description: 'Registro do CMDCA ou CMAS obrigatório para captação via FIA ou Fundo do Idoso.',
    level: 'Prata',
    category: 'Jurídico & Estatutário',
    requiredForLegalCompliance: false,
    checked: true,
  },

  // OURO LEVEL (Avançado)
  {
    id: 'req_o1',
    title: 'Relatório Anual de Impacto Social com Indicadores (KPIs)',
    description: 'Documento quantitativo e qualitativo das entregas, famílias atendidas e impacto na comunidade.',
    level: 'Ouro',
    category: 'Compliance & Impacto',
    requiredForLegalCompliance: false,
    checked: false,
  },
  {
    id: 'req_o2',
    title: 'Auditoria Externa Independente das Contas',
    description: 'Parecer emitido por auditoria independente registrada no CRC/CVM.',
    level: 'Ouro',
    category: 'Financeiro & Contábil',
    requiredForLegalCompliance: false,
    checked: false,
  },
  {
    id: 'req_o3',
    title: 'Código de Ética, Conduta e Política de Proteção Infantil / LGPD',
    description: 'Diretrizes de salvaguarda de beneficiários, prevenção de conflitos de interesse e tratamento de dados.',
    level: 'Ouro',
    category: 'Compliance & Impacto',
    requiredForLegalCompliance: false,
    checked: true,
  },
];

export const MOCK_ONGS: ONG[] = [
  {
    id: 'ong-01',
    name: 'Instituto Educação e Futuro',
    tradeName: 'EducaFuturo',
    cnpj: '48.291.832/0001-94',
    areaAtuacao: 'Educação e Pesquisa',
    state: 'SP',
    city: 'São Paulo',
    foundingYear: 2017,
    mission: 'Garantir reforço escolar, apoio pedagógico e robótica para crianças e jovens da periferia urbana.',
    summary: 'Oferece contraturno escolar com programação, leitura e alimentação nutritiva para mais de 450 crianças.',
    email: 'contato@educafuturo.org.br',
    phone: '(11) 98765-4321',
    website: 'https://educafuturo.org.br',
    pixKey: '48291832000194',
    maturityLevel: 'Prata',
    governanceScore: 78,
    requirements: INITIAL_GOVERNANCE_REQUIREMENTS.map(r => ({ ...r })),
    totalRaisedR$: 340000,
    activeBeneficiariesCount: 450,
    verifiedStatus: true,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'ong-02',
    name: 'Associação Verde Esperança Paranaense',
    tradeName: 'Verde Esperança',
    cnpj: '12.345.678/0001-22',
    areaAtuacao: 'Meio Ambiente e Causa Animal',
    state: 'PR',
    city: 'Curitiba',
    foundingYear: 2015,
    mission: 'Restaurar a Mata Atlântica e promover hortas comunitárias sustentáveis em áreas vulneráveis.',
    summary: 'Projeto de agrofloresta urbana, compostagem e educação ambiental em escolas públicas.',
    email: 'verde@esperanca.org.br',
    phone: '(41) 99123-8822',
    pixKey: 'verde@esperanca.org.br',
    maturityLevel: 'Ouro',
    governanceScore: 92,
    requirements: INITIAL_GOVERNANCE_REQUIREMENTS.map(r => ({ ...r, checked: true })),
    totalRaisedR$: 780000,
    activeBeneficiariesCount: 1200,
    verifiedStatus: true,
    createdAt: '2023-11-20T14:30:00Z',
  },
  {
    id: 'ong-03',
    name: 'Casa do Acolhimento Sombra & Luz',
    tradeName: 'Casa Sombra & Luz',
    cnpj: '33.910.204/0001-50',
    areaAtuacao: 'Assistência Social',
    state: 'PE',
    city: 'Recife',
    foundingYear: 2020,
    mission: 'Acolhimento temporário, capacitação profissional e reinserção social de mulheres e mães solo.',
    summary: 'Oferece oficinas de costura, gastronomia social e atendimento psicológico gratuito.',
    email: 'acolhimento@sombraluz.org.br',
    phone: '(81) 98111-2233',
    pixKey: '33910204000150',
    maturityLevel: 'Bronze',
    governanceScore: 55,
    requirements: INITIAL_GOVERNANCE_REQUIREMENTS.map(r => ({
      ...r,
      checked: r.level === 'Bronze',
    })),
    totalRaisedR$: 120000,
    activeBeneficiariesCount: 210,
    verifiedStatus: true,
    createdAt: '2024-03-01T09:15:00Z',
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-101',
    ongId: 'ong-01',
    ongName: 'Instituto Educação e Futuro',
    title: 'Lab de Robótica e Leitura nas Comunidades',
    summary: 'Instalação de laboratório móvel de robótica e biblioteca comunitária em 3 polos de periferia.',
    description: 'Projeto aprovado no FIA (Fundo da Infância e Adolescência). Vai atender 300 jovens com aulas semanais de lógica, programação Scratch, robótica sustentável e mediação de leitura.',
    mecanismo: 'FIA',
    targetAmountR$: 150000,
    raisedAmountR$: 95000,
    odsList: [4, 9, 10], // ODS 4 Educação de Qualidade, 9 Indústria e Inovação, 10 Redução das Desigualdades
    beneficiariesCount: 300,
    startDate: '2026-03-01',
    endDate: '2026-12-31',
    status: 'Em Captação',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80',
    budgetBreakdown: [
      { item: 'Equipamentos de Robótica & Laptops', amountR$: 60000 },
      { item: 'Bolsa para Educadores de TI & Pedagogos', amountR$: 50000 },
      { item: 'Acervo de Livros & Lanches Nutritivos', amountR$: 25000 },
      { item: 'Gestão, Prestação de Contas e Transporte', amountR$: 15000 },
    ],
  },
  {
    id: 'proj-102',
    ongId: 'ong-02',
    ongName: 'Associação Verde Esperança Paranaense',
    title: 'Hortas Comunitárias e Agroecologia Urbana',
    summary: 'Criação de 5 novas hortas comunitárias gerando alimentos orgânicos para 600 famílias vulneráveis.',
    description: 'Projeto voltado à segurança alimentar e adaptação climática urbana. Conecta voluntários corporativos e moradores da periferia para transição agroecológica.',
    mecanismo: 'Investimento Social Privado',
    targetAmountR$: 220000,
    raisedAmountR$: 180000,
    odsList: [2, 11, 13], // Fome Zero, Cidades Sustentáveis, Ação Contra a Mudança do Clima
    beneficiariesCount: 600,
    startDate: '2026-01-15',
    endDate: '2026-11-30',
    status: 'Em Execução',
    imageUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb12765?w=800&auto=format&fit=crop&q=80',
    budgetBreakdown: [
      { item: 'Insumos Agroecológicos e Ferramentas', amountR$: 70000 },
      { item: 'Infraestrutura de Irrigação Solar', amountR$: 60000 },
      { item: 'Oficinas de Capacitação Nutricional', amountR$: 50000 },
      { item: 'Coordenação de Projeto e Análise de Solo', amountR$: 40000 },
    ],
  },
  {
    id: 'proj-103',
    ongId: 'ong-03',
    ongName: 'Casa do Acolhimento Sombra & Luz',
    title: 'Oficina de Gastronomia Social e Renda Mão na Massa',
    summary: 'Capacitação profissional de 80 mulheres em vulnerabilidade em panificação e confeitaria.',
    description: 'Projeto para promover a autonomia financeira de mães solo através da produção de pães e bolos artesanais, com incentivo à criação de microcooperativas.',
    mecanismo: 'Doação Direta PIX',
    targetAmountR$: 60000,
    raisedAmountR$: 28500,
    odsList: [1, 5, 8], // Erradicação da Pobreza, Igualdade de Gênero, Trabalho Decente
    beneficiariesCount: 80,
    startDate: '2026-04-01',
    endDate: '2026-09-30',
    status: 'Em Captação',
    imageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&auto=format&fit=crop&q=80',
    budgetBreakdown: [
      { item: 'Fornos Industriais e Batedeiras', amountR$: 25000 },
      { item: 'Materia-prima e Insumos Culinários', amountR$: 20000 },
      { item: 'Instrutor de Gastronomia & Mkt Digital', amountR$: 15000 },
    ],
  },
];
